server:
  port: ${PORT}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: server
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  access_time: ${JWT_REFRESH_TIME}
  refresh_time: ${JWT_ACCESS_TIME}


client:
  url: ${CLIENT_URL}